"""Initial migration

Revision ID: 0ce250524ea4
Revises: 5e5fd2356b32
Create Date: 2024-07-07 21:59:27.032327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce250524ea4'
down_revision: Union[str, None] = '5e5fd2356b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('last_trained', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'last_trained')
    # ### end Alembic commands ###
