"""Initial migration

Revision ID: 5b3c3b0c0c05
Revises: 0e6a6cf8436f
Create Date: 2024-07-09 13:38:14.076813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3c3b0c0c05'
down_revision: Union[str, None] = '0e6a6cf8436f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
