"""Initial migration

Revision ID: 9cfdb7e8c87c
Revises: 6ee2e19be5a6
Create Date: 2024-07-09 11:11:12.436739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfdb7e8c87c'
down_revision: Union[str, None] = '6ee2e19be5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('first_message', sa.String(), nullable=False))
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chats', 'first_message')
    # ### end Alembic commands ###
