"""Initial migration

Revision ID: d9aec397fa70
Revises: cd8034960766
Create Date: 2024-07-08 12:55:21.692711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aec397fa70'
down_revision: Union[str, None] = 'cd8034960766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('name', sa.String(), nullable=False))
    op.add_column('domain', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('domain', 'domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('domain', 'url')
    op.drop_column('domain', 'name')
    # ### end Alembic commands ###
