name: Deploy FastAPI to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
        script: |
          cd /root/penguin-backend
          git fetch origin main
          git reset --hard origin/main
          if [ ! -d "venv" ]; then
            virtualenv venv
          fi
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "QDRANT_HOST=${{ secrets.QDRANT_HOST }}" >> .env
          echo "QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

          sudo systemctl restart fastapi.service
